* AMAL language
** Overview
The premise of the AMAL language, is to wrap markdown with markup for animations.

Example:

#+begin_src markdown
  # This is markdown. (this is a header)

  This is normal markdown with *italics*, **bold**, etc...

  @type This is AMAL getting typed out dynamically with *italics*, **bold**, etc...@
#+end_src

** Background
Arielle has a [[https://www.ariellemcmanus.com][personal website]], mostly for her writing work.
She wanted to put a poem on the front page of the website.
She didn't want the poem to just sit there though, she wanted it to be a spectacle - an event.
She wanted it to look as though she was typing the poem out letter-by-letter for whoever visited the site.

She came to me for advice.
I thought we could accomplish this effect with [[https://www.w3schools.com/css/css3_animations.asp][CSS animations]].
It turned out to be too much of a pain in the butt.
We ended up just recording her typing out the poem, and turning that into a GIF.

Still, the idea has stuck in my head.
Why shouldn't there be an ergonomic way to insert animations into website markup?
Her birthday is coming up, and I always try to make something for her for her birthday.
This would be a cool birthday present.
Thus, the =AMAL= language: a language for animated markup.
(In markdown, for the non-animated parts)

** Design
*TO BE FILLED OUT*
