* Arielle language
** Overview
The premise of the arielle language, is to wrap markdown with markup for animations.

Example:

#+begin_src markdown
  # This is markdown. (this is a header)

  This is normal markdown with *italics*, **bold**, etc...

  $type{This is arielle getting typed out dynamically with *italics*, **bold**, etc...}
#+end_src

** Background
Arielle has a [[https://www.ariellemcmanus.com][personal website]], mostly for her writing work.
She wanted to put a poem on the front page of the website.
She didn't want the poem to just sit there though, she wanted it to be a spectacle - an event.
She wanted it to look as though she was typing the poem out letter-by-letter for whoever visited the site.

She came to me for advice.
I thought we could accomplish this effect with [[https://www.w3schools.com/css/css3_animations.asp][CSS animations]].
It turned out to be too much of a pain in the butt.
We ended up just recording her typing out the poem, and turning that into a GIF.

Still, the idea has stuck in my head.
Why shouldn't there be an ergonomic way to insert animations into website markup?
Her birthday is coming up, and I always try to make something for her for her birthday.
This would be a cool birthday present.
Thus, the =arielle= language: a language for animated markup.
(In markdown, for the non-animated parts)

** Design
=arielle= is supposed to be markdown for the static parts, and use a custom syntax for the dynamic parts.
How can we accomplish that?

*** Parse markdown and then parse =arielle=
We could parse markdown to a tree using the existing [[https://docs.racket-lang.org/markdown/][Racket markdown]] reader, and then re-parse the parse tree, inserting =arielle= nodes.

Pros:
1. Split up the parsing steps.
   This allows me to not have to think about markdown syntax in my reader.

Cons:
1. All =arielle= blocks have to be within markdown blocks?
   It seems like it would get really complicated to try to figure out parsing them across multiple markdown blocks

What do we do about a situation like this:

#+begin_src markdown
  Where I have some markdown **syntax $wiggle{interspersed with** `arielle`}
#+end_src

What should the parse-tree look like in that situation?

What does markdown do about similar situations?
Seems like it doesn't really work:

#+begin_src racket
  ;; Putting markup entirely within other markup works fine
  tokenizer.rkt/test> (define xs (parse-markdown "How do we handle *interspersed **text in** here?*"))
  tokenizer.rkt/test> xs
  '((p
     ()
     "How do we handle "
     (em () "interspersed " (strong () "text in") " here?")))

  ;; But interspersed markup is messed up
  tokenizer.rkt/test> (define xs (parse-markdown "How do we handle *interspersed __text* in__ here?"))
  tokenizer.rkt/test> xs
  '((p
     ()
     "How do we handle *interspersed "
     (strong () "text* in")
     " here?"))
#+end_src

I also tested on [[https://markdownlivepreview.com/]], with the same results. So maybe we just say it isn't possible in =arielle=? 

In that case we could [[*Parse markdown and then parse =arielle=][Parse markdown and then parse arielle]].
That's still kind of nasty though, right?
We'd rather not parse twice if we can help it.

We can't go all the way [[https://github.com/nuts4nuts4nuts/12lang/tree/main/beautiful_racket/jsonic-lang][jsonic]] because =jsonic= compiled to json.
We want to compile to HTML, not markdown.

*** /Compile arielle to markdown/, then compile markdown

Okay, we still don't love two passes of parsing, but I'm on a very limited schedule here.
What if we compile =arielle= to markdown, replacing the =arielle= markup with HTML and associated CSS, and then pass that on to be compiled as markdown?
This lets us mostly do the =jsonic= thing, where we just pass along every character that's not relevant to =arielle= markup.
HTML /should/ pass through markdown. Let's test that here to be sure.

#+begin_src racket
  > (define xs (parse-markdown "How does markdown handle *inline <a href='https://www.w3schools.com/html/'>HTML</a>, huh?*"))

  > xs
  
  '((p () "How does markdown handle " (em () "inline " (a ((href "https://www.w3schools.com/html/")) "HTML") ", huh?")))
#+end_src

Wow, it converts it to xexpressions! That makes sense.
Going a little further and rendering it to HTML gives us:

#+begin_src racket
  > (display-xexpr `(html () (head ()) (body () ,@xs)))

  <html>
    <head></head>
    <body>
      <p>
	How does markdown handle <em>inline <a href="https://www.w3schools.com/html/">HTML</a>, huh?</em>
      </p>
    </body>
  </html>
#+end_src

Looks good! How about markdown within an HTML element?

#+begin_src racket
  > (define xs (parse-markdown "How does markdown handle *inline <a href='https://www.w3schools.com/html/'>__HTML__</a>, huh?*"))

  > xs

  '((p () "How does markdown handle " (em () "inline " (a ((href "https://www.w3schools.com/html/")) (strong () "HTML")) ", huh?")))
  
  > (display-xexpr `(html () (head ()) (body () ,@xs)))

  <html>
    <head></head>
    <body>
      <p>How does markdown handle <em>inline <a href="https://www.w3schools.com/html/"><strong>HTML</strong></a>, huh?</em>
      </p>
    </body>
  </html>
#+end_src

Just as we'd expect!
Let's go with this method.

*** What lives in the tokenizer, what lives in the parser?
We are going to compile =arielle= to html, then pass it along to get compiled as markdown.
Given that design, how do we divide the work between the tokenizer and the parser?

We really only care about identifying =arielle= expressions.
Everything else can just get passed along.
But is there a problem if we mis-tokenize parts of =arielle= expressions out of context?
For instance, let's say our grammar is this:

#+begin_src racket
  #lang brag
  a-program : (a-char | a-expr)*
  a-char : CHAR
  a-expr : a-expr-name [a-expr-args] a-expr-body
  a-expr-name : EXPR-NAME
  a-expr-args : "(" [EXPR-KEY ":" EXPR-VALUE ","]* EXPR-KEY ":" EXPR-VALUE ")"
  a-expr-body : EXPR-BODY
#+end_src

- How do we differentiate =EXPR-NAME= from =EXPR-KEY= in the tokenizer?
- Should =EXPR-VALUE= be typed some how (uh oh)?

What if we just tokenize everything into whitespace delimited strings.
Then all of the =EXPR-<whatever>= become =WORD=

#+begin_src racket
  #lang brag
  a-program : (a-char | a-expr)*
  a-char : CHAR
  a-expr : a-expr-name [a-expr-args] a-expr-body
  a-expr-name : "$" WORD
  a-expr-args : "(" [a-arg-key ":" a-arg-value ","]* a-arg-key ":" a-arg-value ")"
  a-arg-key : WORD
  a-arg-value : WORD
  a-expr-body : "{" WORD+ "}"
#+end_src

This kind of makes sense right?
We still have the problem where a-arg-value should probably be typed or something, but that sounds like a problem for a future language update.

Wait then we have a problem with what all of the symbols get lexed as...
I guess they can just get lexed literally and passed on to markdown if they're not part of an =arielle= expression.

Ugh... it's not working.

Really all I want to do is expand =arielle= expressions within markdown and add the associated animation styles to the top of the string.
That's all!
What's the simplest way to do that?

Ultimately what do we want the parse tree to look like?
Maybe something like this:

#+begin_src racket
  (a-program (a-markdown "<STUFF>")
	     (a-expr (a-expr-name "<name>")
		     (a-expr-args (a-arg-key "<key>")
				  (a-arg-value "<value>")
				  ...)
		     (a-expr-body "<STUFF>"))
	     (a-markdown "<MORE STUFF>"))
#+end_src

But how do we differentiate the stuff within the =arielle= blocks from stuff in markdown blocks?
If I wasn't trying to model this as a /"language"/ I would know how to do it...
Maybe I just handle the =arielle= parsing in the expander.
Is that crazy?
Maybe not.
That way we really can do it like jsonic, but we just have to actually handle the =arielle= expressions instead of letting racket handle them.

I spent some more time trying to actually parse this into usable stuff.
Let's stop.
Full jsonic, all the way.

Oh yeah, that doesn't let us nest expressions............................................
What am I going to do?

Idea I had this morning:

- Use mirrored delimiters
- Tokenize to delimiters and words
- Require escapes for literal delimiters

Obviously I've thought this before, but I think this would work!
At the expense of breaking existing markdown with unescaped delimiters but whatever.
I have to finish the damn parser...

WHAT THE FUCK DOES "ENCOUNTERED PARSING ERROR" MEAN!?!?!?!??!?!?!?!?

Guess my whitespace was wrong in the parser...

Note to self: comment out the real parse rule attempt and build up the rule incrementally to debug

I think I can make a programming language out of this!
